In [1]:
import numpy as np
import random

In [5]:
# 450 elemanlı 1-100 arsında rasgele degrlerden olusan tek boyutlu bir ndarray oluşturalım:
x=np.random.randint(1, 100, size=(450,))
print(x)
# aritmetik ortalama= mean
print("x.mean() ")
print(x.mean())
print()
# medyan= median
print("np.median(x) ")
print(np.median(x))
print()
# standart sapma= std()
print("x.std() ")
print(x.std())

[70 33 40 19 24 19 87 16 85 38  6 38 63 17 72  6 97 89 77 81 39 56 66  9
 15 47 41 68 46 33 26 27 10 92 80 17 57 75 39 27 39 19 55 77 32 70 94 98
 31 67  8 69 67 79 40  6 94 20 14 30 91 22 17 20 51 60 80 95 35 89 26 16
 11  4 60 94 20 62 31 74 74 77 65 66 83  6 10 12 35 89 57 42  5 74 36 47
 65 93 51  4 94 54 73 21 26  7 34 61  3 47 27 45 20 97 52  6 22  7 42 81
 74 40 20 59 32 96 71 86 35 47 25 61 94 32 90 31  6 63 53  7 72 94 94 19
 51 31 11 25 91 26 85 10 87 32 38 41 51 93 33 70 84  8 19 91 52 11 50 14
 10 30 93 99 39 60 77 59 43 24 94  2 43 93 67 61 66 54 35 40 89  2 90 54
 50 38 48 15  4 79 19 76 90 42 43 58 44 24 23 12 75 35 70 46 32 32 52 84
 56 45  7 52 72 66 58 84 58 82 17 60 44 69 12 12 87 53 65 44 20 75 51 55
 13 24 23 51 25  8 60  5 53 28 73 80 73 25 22 27 41 41 28 43 27 32 67 37
 29 94 69 96 58 45 78 23 67 25 21 25 59 44 65 50 51 21 47 81 16 43 48 89
 40  7  1 42 44 14 71 58 83 50 78  5 70 89 38 46 73 23 31 75 39 22 96 41
  9 81 51 67 43 66 22 34 87 38 67 92 49 15 71 13 74

In [6]:
# iki boyultu 1-100 arasında rasgele degerlerden oluşan 4X3 lük bir matris oluşturalım:
y=np.random.randint(1, 100, size=(4,3))
print("y")
print(y)
print()
print("y.mean(axis=0) ")
print(y.mean(axis=0)) # y matrisinin sütunlarındaki dgerlerin aritmetik ortalaması
print()
print("np.median(y, axis=1) ")
print(np.median(y, axis=1)) # y matrisinin satırlarındaki degerlerin medyanı 
print()
print("y.std(axis=0) ")
print(y.std(axis=0)) # y matrisinin sütunlarındaki degerlerin standart sapması 


y
[[29 42 36]
 [37 59  1]
 [84 92 16]
 [88 25 51]]

y.mean(axis=0) 
[59.5 54.5 26. ]

np.median(y, axis=1) 
[36. 37. 84. 51.]

y.std(axis=0) 
[26.68801229 24.76388499 19.03943276]
