In [2]:
import numpy as np
import random

In [6]:
x=np.random.randint(1, 10, size=(5,))
print(x)
y=np.random.randint(1, 10, size=(5,))
print(y)
print()
# toplama için add
print(x+y) # + oeratörü add ile ayno işi yapar 
print(np.add(x,y)) # add ile iki ndarray degerleri toplanır
print()
# çıkarma için subtract
print(x-y)
print(np.subtract(x,y))
print()
# çarmpa için multiply
print(x*y)
print(np.multiply(x,y))
print()
# bolme için divide 
print(x/y)
print(np.divide(x,y))


[9 6 6 4 5]
[4 6 2 6 3]

[13 12  8 10  8]
[13 12  8 10  8]

[ 5  0  4 -2  2]
[ 5  0  4 -2  2]

[36 36 12 24 15]
[36 36 12 24 15]

[2.25       1.         3.         0.66666667 1.66666667]
[2.25       1.         3.         0.66666667 1.66666667]


In [7]:
x=np.random.randint(1, 10, size=(5,))
print(x)
print(x+ 3)
print(x - 3)
print(x * 3)
print(x / 3)

[4 5 6 1 2]
[7 8 9 4 5]
[ 1  2  3 -2 -1]
[12 15 18  3  6]
[1.33333333 1.66666667 2.         0.33333333 0.66666667]


In [13]:
x=np.random.randint(1, 10, size=(5,))
y=np.random.randint(1, 10, size=(5,))
print(x)
print(y)
print("arraylerin karşılıklı elemanları eşit mi")
print(x==y)
print("array ler eşitmi : ")
print(np.array_equal(x,y))

[6 1 8 5 4]
[6 5 6 9 6]
arraylerin karşılıklı elemanları eşit mi
[ True False False False False]
array ler eşitmi : 
False


In [14]:
x=np.random.randint(1, 10, size=(5,))
print(x)
# x in degerlerinin karekoku:
print(np.sqrt(x))
# x in degerlerinin 3. kuvveti:
print(np.power(x,3))
# x in degerlerinin logaritmik karşılıkları:
print(np.exp(x))

[1 9 9 7 9]
[1.         3.         3.         2.64575131 3.        ]
[  1 729 729 343 729]
[2.71828183e+00 8.10308393e+03 8.10308393e+03 1.09663316e+03
 8.10308393e+03]


In [20]:
x=np.random.randint(1, 10, size=(9,)).reshape(3,3)
print(x)
# xin elemanlarının toplamı :
print(np.sum(x))
print(x.sum(axis=0)) # x matrisinin sütunlardaki degerlerin toplamı
print(x.sum(axis=1)) # x matrisinin satılardaki degerlerin toplami
# x matrisinin en buyuk ve en kucuk elemanı:
print(x.max())
print(x.min())

[[7 4 7]
 [8 1 1]
 [1 2 4]]
35
[16  7 12]
[18 10  7]
8
1


In [19]:
x1=np.random.randint(1, 10, size=(5,))
print(x1)
# x1 matrisindeki en buyuk ve en kucuk degerlerin index numaralrı:
print(x1.argmin())
print(x1.argmax())

[1 8 6 8 3]
0
1
