In [19]:
#bu bolumde gömülü fonksiyonlara devam edilecektir :
import numpy as np
import random

In [ ]:
#-> arange() metodu :
#arange metodunun arange(baslangic,bitis,adimsayisi) şeklinde parametreleri vardır
#eger sadece bitiş degeri verilirse bitiş değeri dahil olmaycak şekilde 0 dan bitiş değerine kadar bir liste doner
#aşağıdaki kullanımları inceleyelim

In [2]:
#[0,10) aralığında liste bastır :
x=np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#[1,30) aralıgında lite bastır:
x=np.arange(1,30)
print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]


In [4]:
#[2,10,2] 2 10(10 degerinin dahil olmaycagına dikkat edin) aralıgında 2 şer artan bir liste bastir:
x=np.arange(2,10,2)
print(x)

[2 4 6 8]


In [5]:
#NOT: eğer ki başlangıç degeri verilmeden bitiş ve artış mktarı argümanları verilirse yanlış bir kullanım olmuş olur 
#çünkü python hangi degerin nereye gelecegini bilmeycektir sadece kaç parametre aldgını bilir incelyelim:
#yapmaya çalıştığımız şeyi uygulasak:

# 0 ile 10 arsında 2 şer artan 10 a kadar bir liste don ve yazdir:
x=np.arange(10,2)
print(x)

[]


In [ ]:
#-> linspace metodu :
# linspace(baslangiç,bitiş,eleman_sayisi)
#linspace metodu başlangıç ve bitiş aralıgında istenilen eleman sayısı kadar veri üretir 
#NOT: linspace metoduna bitiş değeri listeye dahil edilir !
#aşağıdaki kullanımları inceleyelim:


In [6]:
#[0,15] aralıgında 10 adet deger üreteb bir liste :
x=np.linspace(0, 15, 10)
print(x)

[ 0.          1.66666667  3.33333333  5.          6.66666667  8.33333333
 10.         11.66666667 13.33333333 15.        ]


In [7]:
#NOT: eğer ki linspace metodunda 3.parametre verilmezse N=50 default olarak gelir:
#aşağıdaki kodda 3.parametere verilmediği için [0,20] aralığında 50 deger basar!
x=np.linspace(0,20)
print(x)

[ 0.          0.40816327  0.81632653  1.2244898   1.63265306  2.04081633
  2.44897959  2.85714286  3.26530612  3.67346939  4.08163265  4.48979592
  4.89795918  5.30612245  5.71428571  6.12244898  6.53061224  6.93877551
  7.34693878  7.75510204  8.16326531  8.57142857  8.97959184  9.3877551
  9.79591837 10.20408163 10.6122449  11.02040816 11.42857143 11.83673469
 12.24489796 12.65306122 13.06122449 13.46938776 13.87755102 14.28571429
 14.69387755 15.10204082 15.51020408 15.91836735 16.32653061 16.73469388
 17.14285714 17.55102041 17.95918367 18.36734694 18.7755102  19.18367347
 19.59183673 20.        ]


In [8]:
#NOT: linspace metodunda bitiş parameteresini dahil etmek istemezsek endpoint=False deriz:
x=np.linspace(0,15, endpoint=False)
print(x)

[ 0.   0.3  0.6  0.9  1.2  1.5  1.8  2.1  2.4  2.7  3.   3.3  3.6  3.9
  4.2  4.5  4.8  5.1  5.4  5.7  6.   6.3  6.6  6.9  7.2  7.5  7.8  8.1
  8.4  8.7  9.   9.3  9.6  9.9 10.2 10.5 10.8 11.1 11.4 11.7 12.  12.3
 12.6 12.9 13.2 13.5 13.8 14.1 14.4 14.7]


In [11]:
#-> reshape() metodu:
#uluşturulmuş olan bir ndarray yapsının matrislerini değiştirmek istersek reshapae() metodu 
#kullanırız burada önemli olan orjinal matris ile yeniden şekillendirmeye çalıştığımız 
#matris sonuçta aynı elemana sahip olmalıdır

x=np.arange(20)
print("arange(20) ile oluşan x :")
print(x)
print()
y=np.reshape(x,(4,5))
print("reshape(x, (4,5)) 4X5 matris ile oluşan x :")
print(y)


arange(20) ile oluşan x :
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

reshape(x, (4,5)) 4X5 matris ile oluşan x :
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [13]:
#yukarıdaki örneğin diğer bir kullanımına bakcak olursak:
x = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
print("np.array(0,1,2,3..,8,9) ile oluşan x: ")
print(x)
print("x.reshape(3,2) ile oluşan x: ")
print(x.reshape(5,2)) 

np.array(0,1,2,3..,8,9) ile oluşan x: 
[0 1 2 3 4 5 6 7 8 9]
x.reshape(3,2) ile oluşan x: 
[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


In [15]:
#reshape için başka bir kullanıma bakcak olursak 2 tane 4X4 lük matrisin 
#eleman sayısı 16 + 16 dan 32 dir arange ile 32 elemanlı bir ndarray oluşturalım 
#ve bu ndarrayi reshape metodu ile 2 adet 4X4 lük matris haline dönüştürelim:

x=np.arange(32)
print("arange(32) ile oluşan x: ")
print(x)
print()
y=np.reshape(x, (2,4,4))
print("reshape(x, (2,4,4)) ile olışan x: ")
print(y)


arange(32) ile oluşan x: 
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]

reshape(x, (2,4,4)) ile olışan x: 
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]
  [24 25 26 27]
  [28 29 30 31]]]


In [17]:
#reshape() metodunu bize liste donen fonksiyonda kullanabiliriz:
#şimdi reshape() metodunu linspace() metodu ile kullanalım:

#linspace() ile [0,19] aralıgında 20 adet deger üretelim:
x=np.linspace(0,19,20)
print("linspace(0,19,20) ile oluşturulan x: ")
print(x)
print()
y=np.reshape(x, (2,10))
print("reshape(x, (2,10)) ile oluşturulan x: ")
print(y)
print()
z=np.reshape(x, (4,5))
print("reshape(x, (4,5)) ile oluşturulan x: ")
print(z)




linspace(0,19,20) ile oluşturulan x: 
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19.]

reshape(x, (2,10)) ile oluşturulan x: 
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]

reshape(x, (4,5)) ile oluşturulan x: 
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]]


In [18]:
#NOT: yukarıda yapılan işlemi tek bir satırda yazabiliriz:

z=np.linspace(0,19,20).reshape(2,10)
print(z)


[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14. 15. 16. 17. 18. 19.]]


In [20]:
#ndarray lerin random() metodlarla kulanımı:
#aşağıdaki kullanımları inceleyelim:
#random() metodu [0,1) aralığında rasgele sayılar üretir di 

# [0,1) aralıgında rasgele degerlerden oluşan  2X3 lük bir matris verir:
x=np.random.random((2,3))
print("x-> ")
print(x)

x-> 
[[0.17764689 0.30619067 0.76766637]
 [0.08948598 0.46608397 0.71066721]]


In [21]:
#randint() metodu ile verilen iki aralıkta random degerler üretirdi:

#[3,12] aralıgında  random degrlerden oluşan 2X3 lük bir matris verir:
x=np.random.randint(3,12, size=(3,2))
print(x)

[[ 6  4]
 [ 6  3]
 [10  8]]
