In [1]:
# bu bolumde herhnagi bir ndarrayin alt kümlerine nasıl erişeceğimizi işleyeceğiz:
import numpy as np

In [4]:
# aşağıdaki örnekleri dikkatlice incelyelim:
# ndarray[start:end), ndarray[start:], ndarray[:end)
x=np.arange(10)
print(x)
print()
print("x[2:6]  ")
print(x[2:6])  # [2,6) kapalı aralıgındaki degerler
print()
print("x[4:]  ")
print(x[4:])  # [4,10] kapalı aralıgındaki degerler
print()
print("x[:7]  ")
print(x[:7])  # [0,7) kapalı aralıgındaki degerler
print()
print("x[:-1]  ")
print(x[:-1]) # sondan (10,0] kapalı aralıgındaki degerler
print()
print("x[-4:-2]  ")
print(x[-4:-2]) # sondan [-4,-2) kapalı aralıgındaki degerler
print()


[0 1 2 3 4 5 6 7 8 9]

x[2:6]  
[2 3 4 5]

x[4:]  
[4 5 6 7 8 9]

x[:7]  
[0 1 2 3 4 5 6]

x[:-1]  
[0 1 2 3 4 5 6 7 8]

x[-4:-2]  
[6 7]

