In [2]:
#bu bölümde ndarray dizileri üzerinde CRUD operasyonları işlenecektir
import numpy as np

In [2]:
# tek boyutlu ndarray örneği üzerinden arryin verilerine ulaşalım ve de bazı değerleri değiştirelim:

x=np.arange(5)
print("x-> ", x)
print("x[0]-> ", x[0])
print("x[2]-> ", x[2])
print("x[-1]-> ", x[-1])
print("x[-2]-> ", x[-2])
x[2]=200
print("x[2]=200 den sonra  x[2]-> ", x[2])

x->  [0 1 2 3 4]
x[0]->  0
x[2]->  2
x[-1]->  4
x[-2]->  3
x[2]=200 den sonra  x[2]->  200


In [8]:
# şimdi yukarıdaki benzer işlemleri iki boyutlu ndarray üzerinde yapalım:

x=np.arange(12).reshape(3,4)
print("x-> ")
print(x)
print("-------------")
# x[row,column] 
print("x[0][0]-> ", x[0][0]) # 0
print("x[1][2]-> ", x[1][2]) # 6
print("x[2][3]-> ", x[2][3]) # 11
print("--------------")
print("x[0,0]-> ", x[0,0])
print("x[1,2]-> ", x[1,2])
print("x[2,3]-> ", x[2,3])


x-> 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
-------------
x[0][0]->  0
x[1][2]->  6
x[2][3]->  11
--------------
x[0,0]->  0
x[1,2]->  6
x[2,3]->  11


In [9]:
# tek boyutlu bir ndarray de bir degeri silmek istersek 'delete' kullanırız:

x=np.arange(6)
print(x)
x=np.delete(x, [0,1]) # 0 ve 1. indexteki elemanlar silinir!
print(x)

[0 1 2 3 4 5]
[2 3 4 5]


In [14]:
# delete işlevini tek boyutlu ndarrayde uygulamak için silmek istediğimiz indexi vermemiz yeterli oluyordu 
# ama iki boyutlu bir ndarray de hangi satırda ki hangi sütunu silmek istediğimizi belirtmemiz gerek;
# eğer silmek için bir bir satırı ifade edeceksen ' axis = 0 -> satır ' kullanırız
# eğer silmek için bir sütunu ifade edeceksek ' axis = 1 -> sütun ' kullanırız

x=np.arange(16).reshape(4,4)
print(x)
print()
x=np.delete(x, 1, axis=0) # 1. satır silinecek 
print(x)
print()
x=np.delete(x, 1, axis=1) # 1. sütun silinecek
print(x)
print()
x=np.delete(x, [0,2], axis=1) # 0. ve 2. sütun silinecek
print(x)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 0  1  2  3]
 [ 8  9 10 11]
 [12 13 14 15]]

[[ 0  2  3]
 [ 8 10 11]
 [12 14 15]]

[[ 2]
 [10]
 [14]]


In [5]:
# append metodu ndarrayin sonuna eleman ekler eğer belirli bir yere eleman eklemek istersek;
# insert() metodunu kullanırız. tek boyutlu ndarray lere bakıcak olursak:
# np.insert --> np.insert(ndarray, index, eleman)

x=np.arange(5)
print(x)
x=np.insert(x, 1, 123)
print(x)

[0 1 2 3 4]
[  0 123   1   2   3   4]


In [6]:
x=np.arange(5)
print(x)
x=np.insert(x, 2, [-43,34])
print(x)

[0 1 2 3 4]
[  0   1 -43  34   2   3   4]


In [10]:
# insert işlemini şimdi iki boyutlu ndarray için yapalım :

x=np.arange(9).reshape(3,3)
print(x)
print()
# x matrisinin 1.satırına [-5,9,11] degerlerini ekler :
x=np.insert(x, 1, [-5,9,11], axis=0)
print(x)
print()
# DİKKAT: şimdi matrisimiz 4X3 lük bir matris oldu bir satır daha eklendi.

# x matrisinin 0.sütununa [10,20,30,40] degerlerini ekler: 
x=np.insert(x, 0, [10,20,30,40], axis=1)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 0  1  2]
 [-5  9 11]
 [ 3  4  5]
 [ 6  7  8]]

[[10  0  1  2]
 [20 -5  9 11]
 [30  3  4  5]
 [40  6  7  8]]


In [ ]:
# arin yazılım numpy dersleri 5.ders 40.dk dan itibaren not alınmadı !
# işlenen konu stack konusu.