In [1]:
#bu bolumde numpy da kullanılan gömülü fonksiyonlar işlenecektir .
import numpy as np

In [3]:
#1-> ones() metodu : 
#ones metodu istenilen matris buyuklugunde eleamnları 1 den oluşan bir matris oluştrumaya yarar 
#2-> zeros() metodu :
#zeros metodu istenilen matris buyuklugunde elemanları 0 dan oluşan bir matris oluşturmaya yarar 


x=np.zeros(4)
print("x-> ",x)
print("x.dtype-> ",x.dtype)

#yukarıdakı kod elemanları 0 dan oluşan tek boyutlu 4 elemanlı bir liste oluşturur

x->  [0. 0. 0. 0.]
x.dtype->  float64


In [5]:
y=np.ones(4)
print("y-> ",y)
print("y.dtype-> ",y.dtype)

#yukarıdaki kod elemanları 1 den oluşan tek boyutlu 4 elemanlı bir liste oluşturur

y->  [1. 1. 1. 1.]
y.dtype->  float64


In [7]:
#aşağıdaki kullanımlara dikkat edelim metod((*)) * yerine yazılan şey istenilen matris hakkında boyut ve adet bilgisi verir:
#aşağıdaki (2,3,4) kullannımı: "2 adet  3X4 lük matrisler oluştur "
x=np.zeros((2,3,4), dtype=np.int_)
print("x-> ")
print(x)
print("x.dtype-> ",x.dtype)


x-> 
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
x.dtype->  int32


In [9]:
y=np.ones((3,2,2), dtype=np.int_)
print("y-> ")
print(y)
print("y.dtype-> ",y.dtype)


y-> 
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
y.dtype->  int32


In [10]:
#3-> full() metodu: 
#eğer ki 0 ve 1 den farklı olarak matris degerlerimizin bir sabit degerden oluşmasını istoyorsak full() metodu kullanırız :

#aşağıdaki kullanım : "full((2,3),10 ) elemanları 10 dan oluşan 2X3 lük bir matris" oluştur demek
x=np.full((2,3), 10)
print("x-> ")
print(x)
print("x.dtype-> ",x.dtype)

#NOT: ones() ve zeros() metodları default olarak elemanların veri tipini float64 valırken 
#full() metodu kullandıgı sabitin veri tipini alır  

x-> 
[[10 10 10]
 [10 10 10]]
x.dtype->  int32


In [11]:
#4-> eye() metodu :
#eye metodu istenilen ölçüde bir "birim matris oluşturur ."

x=np.eye(4)
print("x-> ")
print(x)
print("x.dtype-> ",x.dtype)
print()
y=np.eye(5,4)
print("y-> ")
print(y)
print("y.dtype-> ",y.dtype)




x-> 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
x.dtype->  float64

y-> 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]
y.dtype->  float64


In [12]:
#eye() metoduna kullanılcak olan k parametresinin degeri birim matristeki diyagonelin konumu belirler:

x=np.eye(6)
print("x-> ")
print(x)
print()
y=np.eye(6, k=1)
print("y-> ")
print(y)
print()
z=np.eye(6, k=-2)
print("z-> ")
print(z)

#yukarıdaki kodda x in diyagoneli tam oratada y nin ki 1 birin sağ yukarı z ninki 2 birim sol aşağı gelmiş şekilde görünecektir:

x-> 
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

y-> 
[[0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0.]]

z-> 
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]]


In [13]:
#5-> diag() metodu:
#diag metodu birim matriste diyagonun yerine gelmesini istediğimiz degerleri ekler :

x=np.diag([4,5,6,-3])
print("x-> ")
print(x)

x-> 
[[ 4  0  0  0]
 [ 0  5  0  0]
 [ 0  0  6  0]
 [ 0  0  0 -3]]
